name: MyPy Type Checking

on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-requests types-setuptools
          pip install -r requirements_dev.txt

      - name: Run MyPy
        run: mypy .
